name: Build and Deploy
permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "45 12-22 * 6-7 *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install and Build 🔧
        run: |
          npm install
          npm test
          npm run build -- --pathprefix=/footballcal-11ty/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: dist
